# Generated by Django 4.0.4 on 2022-06-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=100, verbose_name='correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del produto')),
                ('nombProduc', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion del Producto')),
                ('imgProd', models.ImageField(blank=True, null=True, upload_to='Producto', verbose_name='Imagen del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('Empresa', models.CharField(max_length=100, verbose_name='Quien preparó el Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_Rol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Rol')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre del Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Ususario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo del Usuario')),
                ('clave', models.CharField(max_length=16, verbose_name='Clave del Usuario')),
                ('rut', models.CharField(max_length=11, verbose_name='Rut del usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comilon.rol')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comilon.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comilon.producto')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comilon.usuario'),
        ),
    ]
