# Generated by Django 4.0.4 on 2022-06-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
