# Generated by Django 4.0.4 on 2022-06-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del produto')),
                ('nombProduc', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion del Producto')),
                ('imgProd', models.ImageField(blank=True, null=True, upload_to='Apoderado', verbose_name='Imagen del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('Empresa', models.CharField(max_length=100, verbose_name='Quien preparó el Producto')),
            ],
        ),
    ]
