# Generated by Django 4.0.4 on 2022-06-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0002_rol_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resgistro',
            new_name='Cliente',
        ),
    ]
