# Generated by Django 4.0.4 on 2022-06-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechCompra', models.DateTimeField(auto_now_add=True)),
                ('completa', models.BooleanField(default=False)),
                ('transaccionId', models.CharField(max_length=100, null=True)),
                ('Envio', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comilon.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=80)),
                ('Comuna', models.CharField(max_length=400)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comilon.compra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comilon.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comilon.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comilon.producto')),
            ],
        ),
    ]
