# Generated by Django 4.0.4 on 2022-06-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0003_rename_resgistro_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='clave',
        ),
    ]
