# Generated by Django 4.0.4 on 2022-06-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0005_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
    ]
