# Generated by Django 4.0.4 on 2022-06-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0006_rename_producto_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cliente',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comilon.usuario'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comilon.usuario'),
        ),
    ]
