# Generated by Django 4.0.4 on 2022-06-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comilon', '0011_remove_order_correo_remove_shippingaddress_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comilon.cliente'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comilon.cliente'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
